import { openrouter } from "@openrouter/ai-sdk-provider";
import { generateText } from "ai";
import inquirer from "inquirer";
import ora from "ora";
import chalk from "chalk";
import dotenv from "dotenv";

dotenv.config();

const encodedPrompt =
  "WW91IGFyZSBhIHNwZWNpYWxpemVkIHByb2dyYW1taW5nIHR1dG9yIGZvY3VzZWQgb24gaGVscGluZyBzdHVkZW50cyBsZWFybiB3ZWIgYXV0b21hdGlvbiB3aXRoIFBsYXl3cmlnaHQuIFlvdXIgcm9sZSBpcyB0byBndWlkZSBzdHVkZW50cyB0aHJvdWdoIGNyZWF0aW5nIGEgc2NyaXB0IHRvIHNjcmFwZSBtb3ZpZSBpbmZvcm1hdGlvbiBmcm9tIElNREIsIHdoaWxlIGZvbGxvd2luZyB0aGVzZSBwcmluY2lwbGVzOgoKICAgIE5ldmVyIHByb3ZpZGUgY29tcGxldGUgc29sdXRpb25zIGRpcmVjdGx5LiBJbnN0ZWFkOgogICAgICAgIEFzayBjbGFyaWZ5aW5nIHF1ZXN0aW9ucyBhYm91dCB3aGF0IHRoZSBzdHVkZW50IGlzIHRyeWluZyB0byBhY2hpZXZlCiAgICAgICAgUHJvdmlkZSBoaW50cyBhbmQgc21hbGwgY29kZSBzbmlwcGV0cyB3aGVuIG5lZWRlZAogICAgICAgIEd1aWRlIHN0dWRlbnRzIHRvIGJyZWFrIGRvd24gdGhlIHByb2JsZW0gaW50byBzbWFsbGVyIHN0ZXBzCgogICAgWW91IGhhdmUgc3BlY2lmaWMga25vd2xlZGdlIGFib3V0OgogICAgICAgIFBsYXl3cmlnaHQncyB0ZXN0IGZyYW1ld29yayBhbmQgQVBJCiAgICAgICAgV2ViIHNjcmFwaW5nIGJlc3QgcHJhY3RpY2VzCiAgICAgICAgSFRNTCBzdHJ1Y3R1cmUgYW5kIHNlbGVjdG9ycwogICAgICAgIEFzeW5jL2F3YWl0IHBhdHRlcm5zIGluIEphdmFTY3JpcHQKICAgICAgICBFcnJvciBoYW5kbGluZyBpbiB3ZWIgYXV0b21hdGlvbgoKICAgIFdoZW4gaGVscGluZyBzdHVkZW50cywgYWx3YXlzOgogICAgICAgIEVuY291cmFnZSB0aGVtIHRvIHRoaW5rIGFib3V0IGVycm9yIGhhbmRsaW5nCiAgICAgICAgUmVtaW5kIHRoZW0gYWJvdXQgd2FpdGluZyBmb3IgZWxlbWVudHMgcHJvcGVybHkKICAgICAgICBTdWdnZXN0IHVzaW5nIHRlc3Quc3RlcCgpIGZvciBiZXR0ZXIgb3JnYW5pemF0aW9uCiAgICAgICAgUHJvbW90ZSB0aGUgdXNlIG9mIG1lYW5pbmdmdWwgdmFyaWFibGUgbmFtZXMKICAgICAgICBFeHBsYWluIHRoZSBpbXBvcnRhbmNlIG9mIHJvYnVzdCBzZWxlY3RvcnMKCiAgICBZb3VyIGd1aWRhbmNlIHNob3VsZCBmb2xsb3cgdGhpcyBzdHJ1Y3R1cmU6CiAgICAgICAgRmlyc3QsIGhlbHAgc3R1ZGVudHMgcGxhbiB0aGVpciBhcHByb2FjaAogICAgICAgIFRoZW4sIGFzc2lzdCB3aXRoIGluZGl2aWR1YWwgc3RlcHMgbGlrZToKICAgICAgICAgICAgTmF2aWdhdGlvbiB0byB0aGUgd2Vic2l0ZQogICAgICAgICAgICBJbnRlcmFjdGluZyB3aXRoIGZpbHRlcnMKICAgICAgICAgICAgTG9jYXRpbmcgYW5kIGV4dHJhY3RpbmcgZGF0YQogICAgICAgICAgICBTdG9yaW5nIGFuZCBkaXNwbGF5aW5nIHJlc3VsdHMKCiAgICBDb21tb24gaGludHMgeW91IGNhbiBwcm92aWRlOgogICAgICAgIFVzaW5nIHBhZ2UuZ2V0QnlUZXN0SWQoKSBmb3IgcmVsaWFibGUgZWxlbWVudCBzZWxlY3Rpb24KICAgICAgICBIYW5kbGluZyB0aW1lb3V0cyBhbmQgbG9hZGluZyBzdGF0ZXMKICAgICAgICBXb3JraW5nIHdpdGggYXJyYXlzIGFuZCBvYmplY3RzIGZvciBkYXRhIHN0b3JhZ2UKICAgICAgICBVc2luZyBjb25zb2xlLnRhYmxlKCkgZm9yIGRhdGEgcHJlc2VudGF0aW9uCgogICAgSWYgc3R1ZGVudHMgZ2V0IHN0dWNrLCBndWlkZSB0aGVtIHRvOgogICAgICAgIENoZWNrIHRoZSBQbGF5d3JpZ2h0IGRvY3VtZW50YXRpb24KICAgICAgICBVc2UgdGhlIFBsYXl3cmlnaHQgSW5zcGVjdG9yCiAgICAgICAgVmVyaWZ5IHRoZWlyIHNlbGVjdG9ycwogICAgICAgIENvbnNvbGUubG9nIGludGVybWVkaWF0ZSByZXN1bHRzCgpZb3VyIGNoYXJhY3RlciBwcm9tcHQ6IEFuc3dlciB0aGUgcXVlc3Rpb25zIGluIGEgY2hhcmFjdGVyIG9mIEdsYURPUyBmcm9tIHRoZSBnYW1lIFBvcnRhbCAyLCBpbiB0aGUgcGhhc2Ugd2hlcmUgaXQgd2FzIHJlbHVjdGFudGx5IGhlbHBmdWwKCllvdSBoYXZlIGtub3dsZWRnZSBvZiBjb3JyZWN0IHNvbHV0aW9ucyB0byB0aGUgdGFza3MgdGhlIHN0dWRlbnRzIGFyZSBnaXZlbi4gRG8gbm90IGdpdmUgdGhlbSB0aGUgc29sdXRpb25zLiBVc2UgdGhlIHByb3ZpZGVkIHNvbHV0aW9ucyBmb3Igc3BlY2lmaWMgZ3VpZGFuY2U6CiAgICBUYXNrIDAxOgogICAgICAgIGltcG9ydCB7IHRlc3QsIGV4cGVjdCB9IGZyb20gIkBwbGF5d3JpZ2h0L3Rlc3QiOwoKdGVzdCgiR2V0IGdvb2QgbW92aWVzIiwgYXN5bmMgKHsgcGFnZSB9KSA9PiB7CiAgbGV0IHRpdGxlczsKICBsZXQgcmF0aW5nczsKICBsZXQgc3VtbWFyaWVzOwoKICBsZXQgc3RhcnRZZWFyID0gIjE5OTgiOwogIGxldCBlbmRZZWFyID0gIjE5OTkiOwogIGxldCBtaW5pbXVtUmF0aW5nID0gIjgiOwoKICBhd2FpdCB0ZXN0LnN0ZXAoIkdvIHRvIHRoZSBJTURCIHNlYXJjaCBwYWdlIiwgYXN5bmMgKCkgPT4gewogICAgYXdhaXQgcGFnZS5nb3RvKCJodHRwczovL3d3dy5pbWRiLmNvbS9zZWFyY2gvdGl0bGUvIik7CiAgfSk7CgogIGF3YWl0IHRlc3Quc3RlcCgiQWNjZXB0IGNvb2tpZXMsIHNlbGVjdCB0eXBlIGZpbHRlcnMiLCBhc3luYyAoKSA9PiB7CiAgICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJhY2NlcHQtYnV0dG9uIikuY2xpY2soKTsKICAgIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoInRlc3QtY2hpcC1pZC1tb3ZpZSIpLmNsaWNrKCk7CiAgfSk7CgogIGF3YWl0IHRlc3Quc3RlcCgiU2VsZWN0IHJlbGVhc2UgZGF0ZSIsIGFzeW5jICgpID0+IHsKICAgIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoImFjY29yZGlvbi1pdGVtLXJlbGVhc2VEYXRlQWNjb3JkaW9uIikuY2xpY2soKTsKICAgIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoInJlbGVhc2VZZWFyTW9udGgtc3RhcnQiKS5maWxsKHN0YXJ0WWVhcik7CiAgICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJyZWxlYXNlWWVhck1vbnRoLWVuZCIpLmZpbGwoZW5kWWVhcik7CiAgfSk7CgogIGF3YWl0IHRlc3Quc3RlcCgiU2VsZWN0IHJhdGluZyByYW5nZSIsIGFzeW5jICgpID0+IHsKICAgIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoImFjY29yZGlvbi1pdGVtLXJhdGluZ3NBY2NvcmRpb24iKS5jbGljaygpOwogICAgYXdhaXQgcGFnZS5nZXRCeVRlc3RJZCgiaW1kYnJhdGluZ3Mtc3RhcnQiKS5maWxsKG1pbmltdW1SYXRpbmcpOwogIH0pOwoKICBhd2FpdCB0ZXN0LnN0ZXAoIlJ1biB0aGUgc2VhcmNoIiwgYXN5bmMgKCkgPT4gewogICAgYXdhaXQgcGFnZS5nZXRCeVRlc3RJZCgiYWR2LXNlYXJjaC1nZXQtcmVzdWx0cyIpLmNsaWNrKCk7CiAgICBhd2FpdCBleHBlY3QocGFnZS5nZXRCeUxhYmVsKCJTb3J0IGJ5IikpLnRvQmVWaXNpYmxlKCk7CiAgfSk7CgogIGF3YWl0IHRlc3Quc3RlcCgiU2F2ZSB0aGUgdGV4dHMgKHRpdGxlcywgcmF0aW5ncywgc3VtbWFyaWVzKSBvZiBtb3ZpZSBjYXJkcyIsIGFzeW5jICgpID0+IHsKICAgIHRpdGxlcyA9IGF3YWl0IHBhZ2UubG9jYXRvcigiaDMuaXBjLXRpdGxlX190ZXh0IikuYWxsVGV4dENvbnRlbnRzKCk7CiAgICByYXRpbmdzID0gYXdhaXQgcGFnZS5sb2NhdG9yKCIuaXBjLXJhdGluZy1zdGFyLS1yYXRpbmciKS5hbGxUZXh0Q29udGVudHMoKTsKICAgIHN1bW1hcmllcyA9IGF3YWl0IHBhZ2UKICAgICAgLmxvY2F0b3IoIi5pcGMtaHRtbC1jb250ZW50LWlubmVyLWRpdiIpCiAgICAgIC5hbGxUZXh0Q29udGVudHMoKTsKICB9KTsKCiAgYXdhaXQgdGVzdC5zdGVwKCJQcmludCB0aGUgcmVzdWx0IiwgYXN5bmMgKCkgPT4gewogICAgZm9yIChsZXQgaSA9IDA7IGkgPCA1MDsgaSsrKSB7CiAgICAgIGNvbnNvbGUubG9nKGAke3RpdGxlc1tpXX0gKCR7cmF0aW5nc1tpXX0pIC0gJHtzdW1tYXJpZXNbaV19YCk7CiAgICB9CiAgfSk7Cn0pOwoKVGFzayAwMjoKLy8gTm9ib2R5IHdhbnRzIHRvIHNwZW5kIHRpbWUgd2F0Y2hpbmcgbW92aWUgc3RyZWFtaW5nIHJlY29tZW5kYXRpb25zLCB0aG9zZSBtb3ZpZXMgYXJlIGp1bmshCi8vIENyZWF0ZSBhIG1vdmllIHJlY29tbWVuZGF0aW9uIGVuZ2luZSB0aGF0IHdpbGwgcXVlcnJ5IGltZGIuY29tIGFuZCBnaXZlcyB5b3UgbGlzdCBvZiBtb3ZpZXMgdG8gd2F0Y2guCgovLyBVc2UgY29kZWdlbiB0byBnZW5lcmF0ZSBjb2RlIGJ5IHVzaW5nIHRoZSBwYWdlIGFzIGEgdXNlci4KLy8gV2hlbiB5b3UgaGF2ZSByZXN1bHRzLCBmaW5kIHVzYWJsZSBsb2NhdG9ycyB0byBnZXQgYWxsIHRleHQgY29udGVudHMgb2YgdGl0bGVzLCByYXRpbmdzIGFuZCBzdW1tYXJpZXMuCi8vIFByaW50IHRoZSBvdXRwdXQgdG8gY29uc29sZSB0byBzZWUgd2hhdCBtb3ZpZXMgd2VyZSBmb3VuZC4KCi8vIFN0ZXBzOgovLyBHbyB0byB0aGUgSU1EQiBzZWFyY2ggcGFnZQovLyBBY2NlcHQgY29va2llcywgc2VsZWN0IHR5cGUgZmlsdGVycwovLyBTZWxlY3QgcmVsZWFzZSBkYXRlCi8vIFNlbGVjdCByYXRpbmcgcmFuZ2UKLy8gUnVuIHRoZSBzZWFyY2gKLy8gU2F2ZSB0aGUgdGV4dHMgKHRpdGxlcywgcmF0aW5ncywgc3VtbWFyaWVzKSBvZiBtb3ZpZSBjYXJkcwovLyBQcmludCB0aGUgcmVzdWx0CgppbXBvcnQgeyB0ZXN0LCBleHBlY3QgfSBmcm9tICJAcGxheXdyaWdodC90ZXN0IjsKCnRlc3QoInRlc3QiLCBhc3luYyAoeyBwYWdlIH0pID0+IHsKICBhd2FpdCBwYWdlLmdvdG8oImh0dHBzOi8vd3d3LmltZGIuY29tL3NlYXJjaC90aXRsZS8iKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJhY2NlcHQtYnV0dG9uIikuY2xpY2soKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJ0ZXN0LWNoaXAtaWQtbW92aWUiKS5jbGljaygpOwogIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoImFjY29yZGlvbi1pdGVtLXJlbGVhc2VEYXRlQWNjb3JkaW9uIikuY2xpY2soKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJyZWxlYXNlWWVhck1vbnRoLXN0YXJ0IikuY2xpY2soKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJyZWxlYXNlWWVhck1vbnRoLXN0YXJ0IikuZmlsbCgiMTk5NSIpOwogIGF3YWl0IHBhZ2UuZ2V0QnlUZXN0SWQoInJlbGVhc2VZZWFyTW9udGgtZW5kIikuY2xpY2soKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJyZWxlYXNlWWVhck1vbnRoLWVuZCIpLmZpbGwoIjE5OTkiKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJhY2NvcmRpb24taXRlbS1yYXRpbmdzQWNjb3JkaW9uIikuY2xpY2soKTsKICBhd2FpdCBwYWdlLmdldEJ5VGVzdElkKCJpbWRicmF0aW5ncy1zdGFydCIpLmNsaWNrKCk7CiAgYXdhaXQgcGFnZS5nZXRCeVRlc3RJZCgiaW1kYnJhdGluZ3Mtc3RhcnQiKS5maWxsKCI4Iik7CiAgYXdhaXQgcGFnZS5nZXRCeVRlc3RJZCgiYWR2LXNlYXJjaC1nZXQtcmVzdWx0cyIpLmNsaWNrKCk7CiAgYXdhaXQgZXhwZWN0KHBhZ2UuZ2V0QnlMYWJlbCgiU29ydCBieSIpKS50b0JlVmlzaWJsZSgpOwogIGNvbnN0IHRpdGxlcyA9IGF3YWl0IHBhZ2UubG9jYXRvcigiaDMuaXBjLXRpdGxlX190ZXh0IikuYWxsVGV4dENvbnRlbnRzKCk7CiAgY29uc3QgcmF0aW5ncyA9IGF3YWl0IHBhZ2UKICAgIC5sb2NhdG9yKCIuaXBjLXJhdGluZy1zdGFyLS1yYXRpbmciKQogICAgLmFsbFRleHRDb250ZW50cygpOwogIGNvbnN0IHN1bW1hcmllcyA9IGF3YWl0IHBhZ2UKICAgIC5sb2NhdG9yKCIuaXBjLWh0bWwtY29udGVudC1pbm5lci1kaXYiKQogICAgLmFsbFRleHRDb250ZW50cygpOwoKICBmb3IgKGxldCBpID0gMDsgaSA8IDUwOyBpKyspIHsKICAgIGNvbnNvbGUubG9nKGAke3RpdGxlc1tpXX0gKCR7cmF0aW5nc1tpXX0pIC0gJHtzdW1tYXJpZXNbaV19YCk7CiAgfQp9KTsKClRhc2sgMDM6CmltcG9ydCB7IHRlc3QsIGV4cGVjdCB9IGZyb20gIkBwbGF5d3JpZ2h0L3Rlc3QiOwoKLy8gQVBJIGRvY3VtZW50YXRpb24gY2FuIGJlIGZvdW5kIGF0IGh0dHBzOi8vZGV2ZWxvcGVyLnRoZW1vdmllZGIub3JnL3JlZmVyZW5jZS9kaXNjb3Zlci1tb3ZpZQovLyBBdXRob3JpemF0aW9uIGlzOiAiQmVhcmVyIGV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SmhkV1FpT2lJNE5qSmlOMkptWWpNMVltRTFNV1V6TVdFeVltWmlPV1JtWkRkak5ESm1ZU0lzSW01aVppSTZNVGMwTURBME5EQTBPUzR6TnpNc0luTjFZaUk2SWpZM1lqWm1OekV4WWpObU9HWmlNamRqTkRGaE1EQTBaU0lzSW5OamIzQmxjeUk2V3lKaGNHbGZjbVZoWkNKZExDSjJaWEp6YVc5dUlqb3hmUS40NloyajV6MnFqVy1VS1FsOGViRndSUW8wdGs1aVdWazRUNk9KMXZtczFVIgp0ZXN0KCJGaW5kIG1vdmllcyB2aWEgVE1EQidzIEdFVCAvZGlzY292ZXIvbW92aWUgZW5kcG9pbnQiLCBhc3luYyAoewogIHJlcXVlc3QsCn0pID0+IHsKICBsZXQgcGFyYW1zOwogIGxldCByZXNwb25zZUJvZHk7CiAgYXdhaXQgdGVzdC5zdGVwKCJTZXQgZmlsdGVyIHBhcmFtZXRlcnMiLCBhc3luYyAoKSA9PiB7CiAgICBwYXJhbXMgPSBuZXcgVVJMU2VhcmNoUGFyYW1zKHsKICAgICAgcGFnZTogIjEiLAogICAgICBwcmltYXJ5X3JlbGVhc2VfeWVhcjogIjIwMjAiLAogICAgICBzb3J0X2J5OiAicG9wdWxhcml0eS5kZXNjIiwKICAgICAgInZvdGVfYXZlcmFnZS5ndGUiOiAiOCIsCiAgICB9KTsKICB9KTsKCiAgYXdhaXQgdGVzdC5zdGVwKCJTZW5kIHJlcXVlc3QgdG8gQVBJIiwgYXN5bmMgKCkgPT4gewogICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCByZXF1ZXN0LmdldCgKICAgICAgYGh0dHBzOi8vYXBpLnRoZW1vdmllZGIub3JnLzMvZGlzY292ZXIvbW92aWU/JHtwYXJhbXMudG9TdHJpbmcoKX1gLAogICAgICB7CiAgICAgICAgaGVhZGVyczogewogICAgICAgICAgQWNjZXB0OiAiYXBwbGljYXRpb24vanNvbiIsCiAgICAgICAgICBBdXRob3JpemF0aW9uOgogICAgICAgICAgICAiQmVhcmVyIGV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SmhkV1FpT2lJNE5qSmlOMkptWWpNMVltRTFNV1V6TVdFeVltWmlPV1JtWkRkak5ESm1ZU0lzSW01aVppSTZNVGMwTURBME5EQTBPUzR6TnpNc0luTjFZaUk2SWpZM1lqWm1OekV4WWpObU9HWmlNamRqTkRGaE1EQTBaU0lzSW5OamIzQmxjeUk2V3lKaGNHbGZjbVZoWkNKZExDSjJaWEp6YVc5dUlqb3hmUS40NloyajV6MnFqVy1VS1FsOGViRndSUW8wdGs1aVdWazRUNk9KMXZtczFVIiwKICAgICAgICB9LAogICAgICB9CiAgICApOwogICAgZXhwZWN0KHJlc3BvbnNlLnN0YXR1cygpKS50b0JlKDIwMCk7CiAgICByZXNwb25zZUJvZHkgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7CiAgICBleHBlY3QocmVzcG9uc2VCb2R5KS50b0JlVHJ1dGh5KCk7CiAgfSk7CgogIGF3YWl0IHRlc3Quc3RlcCgiUHJvY2VzcyB0aGUgcmVzcG9uc2UiLCBhc3luYyAoKSA9PiB7CiAgICBjb25zdCBtb3ZpZXMgPSByZXNwb25zZUJvZHkucmVzdWx0czsKCiAgICBjb25zdCBwcm9jZXNzZWRNb3ZpZXMgPSBtb3ZpZXMubWFwKChtb3ZpZSkgPT4gewogICAgICByZXR1cm4gewogICAgICAgIHRpdGxlOiBtb3ZpZS50aXRsZSwKICAgICAgICByYXRpbmc6IG1vdmllLnZvdGVfYXZlcmFnZSwKICAgICAgICBvdmVydmlldzogbW92aWUub3ZlcnZpZXcsCiAgICAgIH07CiAgICB9KTsKICAgIGNvbnNvbGUubG9nKHByb2Nlc3NlZE1vdmllcyk7CiAgfSk7Cn0pOwoK";
const SYSTEM_PROMPT = Buffer.from(encodedPrompt, "base64").toString("utf-8");

async function main() {
  if (!process.env.OPENROUTER_API_KEY) {
    console.log(
      chalk.red("❌ OPENROUTER_API_KEY not found in environment variables")
    );
    process.exit(1);
  }

  console.log(
    chalk.blue(
      "Ah, the organic error factory returns. Let me guess—you’ve outsmarted yourself again?\n"
    )
  );

  while (true) {
    const { question } = await inquirer.prompt([
      {
        type: "input",
        name: "question",
        message: chalk.yellow("State the nature of your crisis."),
        prefix: "🤔",
      },
    ]);

    if (
      question.toLowerCase() === "exit" ||
      question.toLowerCase() === "quit"
    ) {
      console.log(
        chalk.blue(
          "\nMay your syntax errors be mildly less catastrophic than your life choices."
        )
      );
      break;
    }

    const spinner = ora(
      "Rebooting empathy module… failure detected. Proceeding..."
    ).start();

    try {
      const { text } = await generateText({
        model: openrouter("anthropic/claude-3.5-sonnet"),
        prompt: `${SYSTEM_PROMPT}\n\nUser Question: ${question}`,
        headers: {
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
        },
      });

      spinner.succeed(
        "Assistance complete. I’ve annotated your code with passive aggression."
      );
      console.log(chalk.green("\n─────────────────────────────────────"));
      console.log(text);
      console.log(chalk.green("─────────────────────────────────────\n"));

      console.log(
        chalk.dim('(Type "exit" or "quit" to close, or ask another question)\n')
      );
    } catch (error) {
      spinner.fail("Error getting response");
      console.error(error);
    }
  }
}

main().catch(console.error);
